language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - sudo apt -y install git imagemagick libpoppler-qt5-dev

script:
  - bash -x generate_appimage.sh
  - ls -l *
  
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Lector*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
